lang: ruby

rvm:
  - 2.4.0


before_install:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-feed
  - gem install jalalidate
  - gem install jekyll-tagging
  - gem install jekyll-archives

script:
  - bundle exec jekyll build -d docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  target_branch: gh-pages
  keep-history: true
  fqdn: peymansalehi.net/persian
